# Generated by Django 2.2.1 on 2019-06-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'ученик', 'verbose_name_plural': 'ученики'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='readersReco_second__ff4929_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='first_lang',
            field=models.CharField(blank=True, choices=[('en', 'Английский'), ('de', 'Немецкий'), ('fr', 'Французкий'), ('zh', 'Китайский'), ('it', 'Итальянский')], max_length=2, verbose_name='Первый язык'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_lang',
            field=models.CharField(blank=True, choices=[('en', 'Английский'), ('de', 'Немецкий'), ('fr', 'Французкий'), ('zh', 'Китайский'), ('it', 'Итальянский')], max_length=2, verbose_name='Второй язык'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['second_name', 'first_name', 'middle_name'], name='readersReco_second__6d3348_idx'),
        ),
    ]
