# Generated by Django 2.2.1 on 2019-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecord', '0003_auto_20190629_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Заметки'),
        ),
    ]
