# Generated by Django 2.2.1 on 2020-08-21 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksRecord', '0013_delete_takenbook'),
        ('readersRecord', '0004_auto_20190710_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=False, verbose_name='возвращена?')),
                ('when_taken', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время взятия')),
                ('when_returned', models.DateTimeField(default=datetime.datetime(2020, 9, 10, 4, 7, 30, 178821, tzinfo=utc), verbose_name='Дата и время возврата')),
                ('book_instance', models.ForeignKey(editable=False, limit_choices_to={'status': 0}, on_delete=django.db.models.deletion.CASCADE, to='booksRecord.BookInstance', verbose_name='экземпляр книги')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readersRecord.Student', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'акт взятия книги',
                'verbose_name_plural': 'акты взятия книг',
                'ordering': ['is_returned', 'when_taken'],
                'get_latest_by': 'when_taken',
            },
        ),
        migrations.AddIndex(
            model_name='booktaking',
            index=models.Index(fields=['is_returned'], name='booksOperat_is_retu_ad2996_idx'),
        ),
    ]
