# Generated by Django 2.2.1 on 2020-08-21 05:36

import booksOperations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksOperations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktaking',
            name='when_returned',
            field=models.DateTimeField(default=booksOperations.models.BookTaking.get_return_date, verbose_name='Дата и время возврата'),
        ),
    ]
