# Generated by Django 2.2.1 on 2019-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('second_name', models.CharField(max_length=25, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Официальное наименование книги', max_length=65, unique=True, verbose_name='Наименование')),
                ('annotation', models.TextField(blank=True, help_text='Аннотация книги, взятая с обратной стороны титульного листа. Желательна к заполнению.', max_length=200, verbose_name='Аннотация')),
                ('author', models.ManyToManyField(help_text='Автор или авторы книги, ссылается на :Model:`booksRecord.Author`', to='booksRecord.Author', verbose_name='Автор(-ы)')),
            ],
        ),
    ]
