# Generated by Django 2.2.1 on 2019-06-11 13:10

import booksRecord.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(help_text='Фамилия автора кириллицей', max_length=25, verbose_name='фамилия')),
                ('first_name', models.CharField(help_text='Имя автора кириллицей', max_length=25, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, help_text='Отчество автора кириллицей, необязательно', max_length=25, verbose_name='отчество')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ['second_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Официальное наименование \nиздательства, без слов "Издательство", "ООО", "ПАО" и т. п.', max_length=65, unique=True, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'издательство',
                'verbose_name_plural': 'издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(db_index=True, help_text='Официальное название книги', max_length=65, unique=True, verbose_name='название')),
                ('year_of_publication', models.SmallIntegerField(verbose_name='год издания')),
                ('edition', models.SmallIntegerField(verbose_name='номер издания')),
                ('publication_city', models.CharField(help_text='город издания книги, без "г. "', max_length=30, verbose_name='город издания')),
                ('isbn', models.BigIntegerField(help_text='ISBN код книги, указанный на штрих-коде сзади, уникален для каждого издания', primary_key=True, serialize=False, unique=True, validators=[booksRecord.models.ean13_validator], verbose_name='ISBN код')),
                ('inventory_number', models.SmallIntegerField(help_text='инвентарный номер из Книги Учёта', verbose_name='инвентарный номер')),
                ('authors', models.ManyToManyField(help_text='Автор или авторы книги, ссылается на :Model:`booksRecord.Author`', to='booksRecord.Author', verbose_name='автор(-ы)')),
                ('publisher', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='booksRecord.Publisher', verbose_name='издательство')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
                'ordering': ['name'],
            },
        ),
    ]
