# Generated by Django 2.2.1 on 2019-06-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.PositiveIntegerField(help_text='идентификатор книги, уникальный для каждого экземпляра; совпадает с номером на наклейке со штрихкодом', primary_key=True, serialize=False, unique=True, verbose_name='индивидуальный идентификатор')),
                ('book', models.ForeignKey(help_text='ссылка на модель Книга :Model:`booksRecord.Book`', on_delete=django.db.models.deletion.CASCADE, to='booksRecord.Book', verbose_name='книга')),
            ],
        ),
    ]
