# Generated by Django 2.2.1 on 2019-06-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Официальное наименование \nиздательства, без слов "Издательство", "ООО", "ПАО" и т. п.', max_length=65, unique=True, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'издательство',
                'verbose_name_plural': 'издательства',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['second_name', 'first_name', 'middle_name'], 'verbose_name': 'автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Автор или авторы книги, ссылается на :Model:`booksRecord.Author`', to='booksRecord.Author', verbose_name='автор(-ы)'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.SmallIntegerField(default=999, verbose_name='номер издания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='inventory_number',
            field=models.SmallIntegerField(default=999, verbose_name='инвентарный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_city',
            field=models.CharField(default=999, help_text='город издания книги, без "г. "', max_length=30, verbose_name='город издания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publishing',
            field=models.SmallIntegerField(default=999, verbose_name='год издания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Имя автора кириллицей', max_length=25, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Отчество автора кириллицей, необязательно', max_length=25, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(help_text='Фамилия автора кириллицей', max_length=25, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, help_text='Официальное название книги', max_length=65, unique=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_index=False, default=999, on_delete=django.db.models.deletion.PROTECT, to='booksRecord.Publisher', verbose_name='издательство'),
            preserve_default=False,
        ),
    ]
