# Generated by Django 2.2.1 on 2019-06-10 10:09

import booksRecord.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0002_auto_20190605_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(default=666, validators=[booksRecord.models.ean13_validator]),
            preserve_default=False,
        ),
    ]
