# Generated by Django 2.2.1 on 2019-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0002_bookinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Имя кириллицей', max_length=25, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Отчество кириллицей, необязательно', max_length=25, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(help_text='Фамилия кириллицей', max_length=25, verbose_name='фамилия'),
        ),
    ]
