# Generated by Django 2.2.1 on 2019-06-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0002_auto_20190614_1704'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='booksRecord_second__450692_idx',
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['second_name', 'first_name', 'middle_name'], name='booksRecord_second__adb239_idx'),
        ),
    ]
