# Generated by Django 2.2.1 on 2019-06-10 15:52

import booksRecord.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0003_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishing_city',
            new_name='publication_city',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='year_of_publishing',
            new_name='year_of_publication',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.SmallIntegerField(help_text='инвентарный номер из Книги Учёта', verbose_name='инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(help_text='ISBN код книги, указанный на штрих-коде сзади, уникален для каждого издания', primary_key=True, serialize=False, unique=True, validators=[booksRecord.models.ean13_validator], verbose_name='ISBN код'),
        ),
    ]
