# Generated by Django 2.2.1 on 2019-06-25 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0004_auto_20190625_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenbook',
            name='book',
        ),
        migrations.AddField(
            model_name='takenbook',
            name='book_instance',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, to='booksRecord.BookInstance', verbose_name='книга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='when_returned',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 54, 43, 803494, tzinfo=utc), verbose_name='Дата и время возврата'),
        ),
    ]
