# Generated by Django 2.2.1 on 2019-06-29 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0005_auto_20190625_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['id'], 'verbose_name': 'экземпляр книги', 'verbose_name_plural': 'экземпляры книг'},
        ),
        migrations.AlterModelOptions(
            name='takenbook',
            options={'get_latest_by': 'when_taken', 'ordering': ['when_taken'], 'verbose_name': 'взятый экземпляр книги', 'verbose_name_plural': 'взятые экземпляры книг'},
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'в хранилище'), (1, 'на руках'), (2, 'истёк срок возврата'), (3, 'снята с учёта')], default=0, editable=False, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='takenbook',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='возвращена?'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(db_index=False, help_text='ссылка на модель Книга :Model:`booksRecord.Book`', on_delete=django.db.models.deletion.CASCADE, to='booksRecord.Book', verbose_name='книга'),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='book_instance',
            field=models.ForeignKey(limit_choices_to={'status': 0}, on_delete=django.db.models.deletion.CASCADE, to='booksRecord.BookInstance', verbose_name='книга'),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='when_returned',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 7, 40, 18, 164828, tzinfo=utc), verbose_name='Дата и время возврата'),
        ),
    ]
