# Generated by Django 2.2.1 on 2019-06-29 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0006_auto_20190629_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenbook',
            name='when_returned',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 7, 40, 43, 791664, tzinfo=utc), verbose_name='Дата и время возврата'),
        ),
    ]
