# Generated by Django 2.2.1 on 2019-06-29 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0007_auto_20190629_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'в хранилище'), (1, 'на руках'), (2, 'истёк срок возврата'), (3, 'снята с учёта')], default=0, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='when_returned',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 10, 5, 16, 521910, tzinfo=utc), verbose_name='Дата и время возврата'),
        ),
    ]
