# Generated by Django 2.2.1 on 2019-07-10 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0010_auto_20190705_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.PositiveSmallIntegerField(help_text='инвентарный номер из Книги Учёта', unique=True, verbose_name='инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'в хранилище'), (1, 'на руках'), (2, 'истёк срок возврата'), (3, 'снята с учёта')], default=0, editable=False, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, help_text='Официальное наименование издательства без слов "Издательство", "ООО", "ПАО" и т. п.', max_length=65, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readersRecord.Student', verbose_name='ученик'),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='when_returned',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 10, 23, 21, 585423, tzinfo=utc), verbose_name='Дата и время возврата'),
        ),
    ]
