# Generated by Django 2.2.1 on 2020-08-20 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecord', '0011_auto_20190710_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takenbook',
            options={'get_latest_by': 'when_taken', 'ordering': ['is_returned', 'when_taken'], 'verbose_name': 'акт взятия книги', 'verbose_name_plural': 'акты взятия книг'},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='booksRecord_grade_5f3938_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='DEF_VAL', max_length=200, verbose_name='автор(-ы)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=20, verbose_name='издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='предмет'),
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='when_returned',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 7, 0, 45, 779700, tzinfo=utc), verbose_name='Дата и время возврата'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['grade', 'subject'], name='booksRecord_grade_1a6f75_idx'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
